In [2]:
import numpy as np
arr=np.arange(1,17).reshape(4,4)
a=arr[2:4,2:4]#row start: row end and column start: column end
print(arr)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[11 12]
 [15 16]]


2

In [4]:
arr=np.random.randint(1,10,(3,3))
print(arr)
print('\nfalttened',arr.flatten())# 2d and 3d -> 1d

[[4 4 9]
 [6 1 9]
 [1 4 4]]

falttened [4 4 9 6 1 9 1 4 4]


In [ ]:
arr=np.random.randint(1,21,10)#10-> total number to generate

print(arr)
print(np.cumsum(arr))
print(np.cumprod(arr))


9.8
[ 9 15 10 14  5 12 12  8  8  5]
[ 9 24 34 48 53 65 77 85 93 98]
[         9        135       1350      18900      94500    1134000
   13608000  108864000  870912000 4354560000]


In [9]:
a=np.linspace(10,50,15)
print(a.reshape(3,5))

[[10.         12.85714286 15.71428571 18.57142857 21.42857143]
 [24.28571429 27.14285714 30.         32.85714286 35.71428571]
 [38.57142857 41.42857143 44.28571429 47.14285714 50.        ]]


In [ ]:
arr=np.random.randint(1,100,10)
print(arr)
print(np.sort(arr)[::-1])#decresing order
print(np.argmax(arr))#It returns the index (position) of the largest value in the array

[79 12 90 41 89 14 38 85 66 86]
[90 89 86 85 79 66 41 38 14 12]
2


In [21]:
while True:
    a=np.random.randint(1,10,(3,3))
    if np.linalg.det(a)!=0:
        break
print(a)
print(np.linalg.det(a))
print(np.linalg.inv(a))

[[8 2 7]
 [2 4 6]
 [3 9 9]]
-101.99999999999996
[[ 1.76470588e-01 -4.41176471e-01  1.56862745e-01]
 [ 2.01858732e-17 -5.00000000e-01  3.33333333e-01]
 [-5.88235294e-02  6.47058824e-01 -2.74509804e-01]]


In [25]:
a=np.array([[1,2],[3,4]])
val, vec= np.linalg.eig(a)
print(val)
print(vec)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [27]:
a=np.random.randint(1,20,10)
print(a)
print(np.where((a%2==0)&(a>5)))

[19  3  7  8 13  8  3 10  7  4]
(array([3, 5, 7]),)


In [29]:
a=np.random.randint(1,20,10)
b=np.random.randint(1,20,10)
c=np.random.randint(1,20,10)
print(np.concatenate((a,b,c)))

[13 13 10  1  3 15  1  4  6 17 11 10  2 13  7 13  3 12  1 17  9 19  3 18
  7 18  7 14  5  1]


In [30]:
X=np.linspace(0,2*np.pi,100)
fft=np.fft.fft(X)   
print(fft)

[314.15926536+0.00000000e+00j  -3.17332591+1.00976868e+02j
  -3.17332591+5.04385710e+01j  -3.17332591+3.35702816e+01j
  -3.17332591+2.51194611e+01j  -3.17332591+2.00355913e+01j
  -3.17332591+1.66351570e+01j  -3.17332591+1.41966440e+01j
  -3.17332591+1.23592884e+01j  -3.17332591+1.09226594e+01j
  -3.17332591+9.76649292e+00j  -3.17332591+8.81425180e+00j
  -3.17332591+8.01490635e+00j  -3.17332591+7.33312351e+00j
  -3.17332591+6.74366083e+00j  -3.17332591+6.22800277e+00j
  -3.17332591+5.77225841e+00j  -3.17332591+5.36580108e+00j
  -3.17332591+5.00036152e+00j  -3.17332591+4.66940728e+00j
  -3.17332591+4.36770841e+00j  -3.17332591+4.09102712e+00j
  -3.17332591+3.83589209e+00j  -3.17332591+3.59943170e+00j
  -3.17332591+3.37924887e+00j  -3.17332591+3.17332591e+00j
  -3.17332591+2.97995138e+00j  -3.17332591+2.79766312e+00j
  -3.17332591+2.62520350e+00j  -3.17332591+2.46148389e+00j
  -3.17332591+2.30555623e+00j  -3.17332591+2.15659006e+00j
  -3.17332591+2.01385386e+00j  -3.17332591+1.87669971e+0

In [ ]:
a=np.random.randint(1,10,(4,3))
print(a+5)# we can apply any type of the operation arthemetic

[[ 8  8  6]
 [13  6 14]
 [ 9  6  9]
 [ 9 14  7]]


In [34]:
m=np.random.randint(1,10,(3,3))
v=np.array([1,2,3])
print(m+v)

[[ 9  6  4]
 [ 8  3 11]
 [ 7  5  7]]


In [35]:
m=np.random.randint(0,10,(4,5))
v=np.random.randint(1,10,5)
print(m-v)


[[-4 -2 -6 -5 -2]
 [-2  0  0 -2  3]
 [-4  6 -2 -2 -2]
 [-4  4 -4 -2 -3]]


In [37]:
m=np.random.randint(1,10,(5,4))
v=np.random.randint(1,10,5)
print(m*v[:,None])


[[ 9  2  5  1]
 [72 32 40 56]
 [25  5 35 30]
 [24 24  8 16]
 [ 4  1  7  8]]


In [38]:
a=np.arange(10).reshape(10,1)
print(a*5)

[[ 0]
 [ 5]
 [10]
 [15]
 [20]
 [25]
 [30]
 [35]
 [40]
 [45]]


In [39]:
m=np.random.randint(1,20,(3,4))
v=np.array([1,2,3,4])
print(m/v)

[[5.         7.5        6.         2.5       ]
 [9.         6.         6.33333333 4.75      ]
 [8.         7.5        2.         2.5       ]]


In [40]:
a=np.random.randint(1,10,(2,3,4))
b=np.random.randint(1,10,(3,4))
print(a+b)

[[[14  9  9 17]
  [10  5 12  7]
  [ 8  8  7 11]]

 [[13 11 15 10]
  [ 4 11 11  5]
  [ 7 12  7 12]]]
