In [1]:
#1d
import numpy as np 
a=np.array([1,2,3], dtype='int32')
print(a)
a.ndim
b=np.array([[1,2,4],[3,4,5]])
print(b)
b.ndim

[1 2 3]
[[1 2 4]
 [3 4 5]]


2

In [2]:
a.shape #Meaning of (3,):

# 3 → total elements

# , → tells Python this is a tuple with one value

(3,)

In [3]:
b.shape # row, coloumn

(2, 3)

In [4]:
print(a)
print(a.dtype)


[1 2 3]
int32


In [12]:
import numpy as np

a = np.array([1,2,3], dtype='int32')

print(a)
print(a.dtype)
a.itemsize
a.nbytes #similar to a.size * a.itemsize
b.dtype


[1 2 3]
int32


dtype('int64')

In [5]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
a.shape

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


(2, 7)

In [6]:
# to get the specific element a[r, c]
print(a[1,5])
print(a[1,-4])

13
11


In [7]:
#to get the specific row a[0, :] and coloumn a[:, 2]
a[0, :]


array([1, 2, 3, 4, 5, 6, 7])

In [8]:
a[:, 3]

array([ 4, 11])

In [9]:
#for getting in a range[startingindex:endingindex:stepsize]
a[0, 1:-2:2]

array([2, 4])

In [10]:
#update the element 
a[1,4]=20
print(a)
a[:, 2]=5
print(a)
a[:,2]=[1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 20 13 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 20 13 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 20 13 14]]


In [11]:
import numpy as np
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((4,2,2), dtype='int32')


array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [14]:
np.full((2,3), 99)

array([[99, 99, 99],
       [99, 99, 99]])

In [15]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
np.full(a.shape,4)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [16]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [17]:
np.random.rand(4,2,3) #random decimal number 

array([[[0.84071307, 0.70062637, 0.95783954],
        [0.53086911, 0.22888775, 0.19611371]],

       [[0.58069691, 0.459015  , 0.08176332],
        [0.12194293, 0.52368929, 0.03574284]],

       [[0.9609096 , 0.6074663 , 0.94975638],
        [0.40696875, 0.54710979, 0.27560879]],

       [[0.47831228, 0.36362355, 0.30068067],
        [0.47865518, 0.24951263, 0.27108715]]])

In [18]:
np.random.random_sample(a.shape)

array([[0.18907964, 0.01430824, 0.62801197, 0.55339421, 0.06093257,
        0.56331315, 0.04473749],
       [0.32133855, 0.6016793 , 0.13815036, 0.94845636, 0.20671597,
        0.97715096, 0.25405683]])

In [19]:
#random integer number
np.random.randint(7, size=(3,3))

array([[2, 4, 5],
       [3, 3, 6],
       [0, 6, 2]], dtype=int32)

In [20]:
#np.random.randint(4, 7, size=(3,3)) generates a 3×3 matrix filled with random integers between 4 and 6 (7 is excluded). Each time you run it, the values change because they are randomly generated.
np.random.randint(4,7,size=(3,3))

array([[6, 5, 4],
       [6, 5, 6],
       [4, 6, 6]], dtype=int32)

In [21]:
np.random.randint(-4, 8, size=(3,3))

array([[ 7, -1, -4],
       [ 1,  6, -3],
       [-1,  5,  7]], dtype=int32)

In [22]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
import numpy as np #repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr, 3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [24]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
print(z)
z[1,1]=9
print(z)
output[1:4,1:4]=z #replaces the middle 3×3 part of output with matrix z using NumPy slicing.
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


****be careful when the copying the array

In [25]:
a=np.array([1,2,3])
b=a
b[0]=100
print(a)
#b=a creates a reference, not a copy, so modifying b also changes a.

[100   2   3]


In [26]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)#Then changes in b will NOT affect a.

[1 2 3]


MATHEMATICS

In [27]:
a=np.array((1,2,3,4))
a+2
print(a)

[1 2 3 4]


In [28]:
a-2

array([-1,  0,  1,  2])

In [29]:
a*2

array([2, 4, 6, 8])

In [30]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [31]:
a+2
a

array([1, 2, 3, 4])

In [32]:
b=np.array((1,0,1,0))
a+b

array([2, 2, 4, 4])

In [33]:
a**2

array([ 1,  4,  9, 16])

In [34]:
#SIN AND COS
np.sin(a)

#np.cos(a)


array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

LINEAR ALGEBRA

In [35]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
np.matmul(a,b) 
#np.matmul(a,b) performs matrix multiplication: rows of a are multiplied with columns of b, producing a new matrix whose shape is (2,2).

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [36]:
#to find the determinant
c=np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [37]:
# to know linear algebra fiunction go with freecodecamp github

STATISTICS

In [38]:
a=np.array(([1,2,3],[4,5,6]))
a

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
np.min(a, axis=1)

array([1, 4])

In [40]:
np.max(a, axis=1)

array([3, 6])

In [41]:
np.sum(a, axis=0)

array([5, 7, 9])

copy() function and broadcast

In [42]:
import numpy as np
arr=np.arange(0,10)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [43]:
arr[3:]=100
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [44]:
arr1=arr.copy()
arr1[3:]=1000
print(arr1)


[   0    1    2 1000 1000 1000 1000 1000 1000 1000]


In [45]:
val=2
arr<2

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [46]:
arr[arr<2]

array([0, 1])

In [47]:
arr2=np.arange(0,10).reshape(5,2)
arr2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [48]:
np.ones((2,5),dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
import numpy as np
y=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]]
)

In [5]:
result=np.hsplit(y,2)
result

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [7]:
result2=np.vsplit(y,2)
result2

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]