In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])
print(a*2)

[2 4 6]


In [6]:
a1=np.array([[1,2],[3,4]])
a1

array([[1, 2],
       [3, 4]])

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((1,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [11]:
np.full((2,4),4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [ ]:
np.eye(3)#identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Conclusion
- Use np.identity() → when you just want a simple square identity matrix
- Use np.eye() → when you need flexibility (real-world use)

In [19]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [24]:
a=np.array([[1,2,3],[4,5,6]])
a.shape
np.full(a.shape,4)

array([[4, 4, 4],
       [4, 4, 4]])

In [25]:
np.full_like(a,4)

array([[4, 4, 4],
       [4, 4, 4]])

In [28]:
np.random.rand(4,1,5)

array([[[0.46539635, 0.31513965, 0.48973231, 0.83564395, 0.45891545]],

       [[0.76244769, 0.55966146, 0.24083382, 0.16030954, 0.43609049]],

       [[0.58406256, 0.19697938, 0.51077274, 0.41057804, 0.46048219]],

       [[0.17935662, 0.74838237, 0.12868625, 0.28449227, 0.49821783]]])

In [32]:
print(np.random.randint(1,10,100))


[1 5 9 3 8 7 8 1 8 2 4 5 6 9 4 7 8 8 3 2 7 5 3 3 2 6 9 5 6 5 9 1 2 1 9 6 3
 8 6 1 1 7 5 9 3 1 3 6 5 9 9 1 4 1 6 4 7 2 2 2 6 8 3 5 2 8 9 6 3 8 9 2 3 4
 8 7 6 5 2 7 9 5 6 1 4 5 4 5 6 5 1 1 7 8 8 3 8 8 2 3]


In [5]:
np.random.randint(10,size=(2,3))

array([[4, 0, 6],
       [3, 4, 8]], dtype=int32)

In [8]:
d=np.random.randint(10, size=(2,3))
d

array([[0, 9, 8],
       [7, 6, 7]], dtype=int32)

In [9]:
np.ndim(d)

2

In [11]:
d.shape

(2, 3)

In [16]:
d.reshape(3,2)

array([[0, 9],
       [8, 7],
       [6, 7]], dtype=int32)

Each element takes 8 bytes (because default dtype is int64)

In [ ]:
d1=np.array([1,2,3,4])
d1.itemsize#int64
d.itemsize#int32

4

In [ ]:
d1.nbytes#4 element x 8 byte for d1 =32

32

In [22]:
a=np.array([[1,2,3,4],[5,6,7,8]])

In [25]:
print(a[1,3])
print(a[-2,2])

8
3


In [33]:
print(a[:,1])
print(a[1,:])
print(a[0,1:-1:2])
a[1,2]=1
print(a)
a[1,:]=2
print(a)

[2 6]
[5 6 1 8]
[2]
[[1 2 3 4]
 [5 6 1 8]]
[[1 2 3 4]
 [2 2 2 2]]


In [36]:
a=np.array([1,2,3,4])
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [38]:
a=np.array([1,2,3,4])
b=a.copy()
b[0]=100
print(a)

[1 2 3 4]


In [41]:
a=np.ones((2,3))
b=np.full((3,2),2)
print(b)
np.matmul(a,b)

[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [45]:
c=np.ones((3,3))
np.linalg.det(c)

np.float64(0.0)

⚠️ Problem

- You have 9 elements
- But you are trying to reshape into 10 elements

❌ Not possible → hence error:

ValueError: cannot reshape array of size 9 into shape (5,2)

In [50]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
a=np.random.randint(1,10,2)
np.where(a%2==0)&(a>2)

array([[1, 0]])