In [1]:
import numpy as np
arr=np.arange(1,17).reshape(4,4)
a=arr[2:4,2:4]#row start: row end and column start: column end
print(arr)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[11 12]
 [15 16]]


2

In [2]:
arr=np.random.randint(1,10,(3,3))
print(arr)
print('\nfalttened',arr.flatten())# 2d and 3d -> 1d

[[7 6 1]
 [1 3 9]
 [1 8 7]]

falttened [7 6 1 1 3 9 1 8 7]


In [3]:
arr=np.random.randint(1,21,10)#10-> total number to generate

print(arr)
print(np.cumsum(arr))
print(np.cumprod(arr))


[16 15 17 19  2 10 13  7 12  8]
[ 16  31  48  67  69  79  92  99 111 119]
[         16         240        4080       77520      155040     1550400
    20155200   141086400  1693036800 13544294400]


In [4]:
a=np.linspace(10,50,15)
print(a.reshape(3,5))

[[10.         12.85714286 15.71428571 18.57142857 21.42857143]
 [24.28571429 27.14285714 30.         32.85714286 35.71428571]
 [38.57142857 41.42857143 44.28571429 47.14285714 50.        ]]


In [5]:
arr=np.random.randint(1,100,10)
print(arr)
print(np.sort(arr)[::-1])#decresing order
print(np.argmax(arr))#It returns the index (position) of the largest value in the array

[26  1 44 48 12 76 92 45 54 30]
[92 76 54 48 45 44 30 26 12  1]
6


In [6]:
while True:
    a=np.random.randint(1,10,(3,3))
    if np.linalg.det(a)!=0:
        break
print(a)
print(np.linalg.det(a))
print(np.linalg.inv(a))

[[6 9 8]
 [6 8 9]
 [9 8 4]]
81.00000000000003
[[-0.49382716  0.34567901  0.20987654]
 [ 0.7037037  -0.59259259 -0.07407407]
 [-0.2962963   0.40740741 -0.07407407]]


In [7]:
a=np.array([[1,2],[3,4]])
val, vec= np.linalg.eig(a)
print(val)
print(vec)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [8]:
a=np.random.randint(1,20,10)
print(a)
print(np.where((a%2==0)&(a>5)))

[ 9  9 12 17  5  3  7  6  1  1]
(array([2, 7]),)


In [9]:
a=np.random.randint(1,20,10)
b=np.random.randint(1,20,10)
c=np.random.randint(1,20,10)
print(np.concatenate((a,b,c)))

[10 16  3 10 11  8 14 19  2  4 16  1 13 17 10 10  4 17 11  5 10  2  2  6
  2 17  7 17 17 13]


In [10]:
X=np.linspace(0,2*np.pi,100)
fft=np.fft.fft(X)   
print(fft)

[314.15926536+0.00000000e+00j  -3.17332591+1.00976868e+02j
  -3.17332591+5.04385710e+01j  -3.17332591+3.35702816e+01j
  -3.17332591+2.51194611e+01j  -3.17332591+2.00355913e+01j
  -3.17332591+1.66351570e+01j  -3.17332591+1.41966440e+01j
  -3.17332591+1.23592884e+01j  -3.17332591+1.09226594e+01j
  -3.17332591+9.76649292e+00j  -3.17332591+8.81425180e+00j
  -3.17332591+8.01490635e+00j  -3.17332591+7.33312351e+00j
  -3.17332591+6.74366083e+00j  -3.17332591+6.22800277e+00j
  -3.17332591+5.77225841e+00j  -3.17332591+5.36580108e+00j
  -3.17332591+5.00036152e+00j  -3.17332591+4.66940728e+00j
  -3.17332591+4.36770841e+00j  -3.17332591+4.09102712e+00j
  -3.17332591+3.83589209e+00j  -3.17332591+3.59943170e+00j
  -3.17332591+3.37924887e+00j  -3.17332591+3.17332591e+00j
  -3.17332591+2.97995138e+00j  -3.17332591+2.79766312e+00j
  -3.17332591+2.62520350e+00j  -3.17332591+2.46148389e+00j
  -3.17332591+2.30555623e+00j  -3.17332591+2.15659006e+00j
  -3.17332591+2.01385386e+00j  -3.17332591+1.87669971e+0

In [11]:
a=np.random.randint(1,10,(4,3))
print(a+5)# we can apply any type of the operation arthemetic

[[11 13  9]
 [10 13 10]
 [10  6 12]
 [11  6 12]]


In [12]:
m=np.random.randint(1,10,(3,3))
v=np.array([1,2,3])
print(m+v)

[[10  9  7]
 [ 3  4  5]
 [10 11  7]]


In [13]:
m=np.random.randint(0,10,(4,5))
v=np.random.randint(1,10,5)
print(m-v)


[[-4 -7  3  0  3]
 [-6 -7  4  6  7]
 [-2 -7  0  1  3]
 [-8 -3  2  7  5]]


In [14]:
m=np.random.randint(1,10,(5,4))
v=np.random.randint(1,10,5)
print(m*v[:,None])


[[ 4  9  5  3]
 [49 14 49 28]
 [ 1  6  1  6]
 [25 45 10 20]
 [21 18  9  9]]


In [15]:
a=np.arange(10).reshape(10,1)
print(a*5)

[[ 0]
 [ 5]
 [10]
 [15]
 [20]
 [25]
 [30]
 [35]
 [40]
 [45]]


In [16]:
m=np.random.randint(1,20,(3,4))
v=np.array([1,2,3,4])
print(m/v)

[[ 2.          3.5         6.          4.        ]
 [16.          4.          6.          2.75      ]
 [13.          4.          0.66666667  2.5       ]]


In [17]:
a=np.random.randint(1,10,(2,3,4))
b=np.random.randint(1,10,(3,4))
print(a+b)

[[[11  3 16 14]
  [11 17  6 14]
  [ 7  7 11 10]]

 [[11  8 15  7]
  [14 18  8 14]
  [ 6  5 10 11]]]
